ERROR - 2024-05-03 05:34:28 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 D:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'ci4', 3306, '', 0)
#1 D:\xampp\htdocs\ci4\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\ci4\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 D:\xampp\htdocs\ci4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\ci4\system\Validation\Validation.php(308): CodeIgniter\Validation\Rules->is_unique('shambhu@rightfu...', 'email', Array, NULL)
#6 D:\xampp\htdocs\ci4\system\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'shambhu@rightfu...', Array, Array)
#7 D:\xampp\htdocs\ci4\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 D:\xampp\htdocs\ci4\app\Controllers\SignupController.php(27): CodeIgniter\Controller->validate(Array)
#9 D:\xampp\htdocs\ci4\system\CodeIgniter.php(898): App\Controllers\SignupController->store()
#10 D:\xampp\htdocs\ci4\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
#11 D:\xampp\htdocs\ci4\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\xampp\htdocs\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 D:\xampp\htdocs\ci4\system\Commands\Server\rewrite.php(43): require_once('D:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 D:\xampp\htdocs\ci4\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\ci4\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 D:\xampp\htdocs\ci4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\ci4\system\Validation\Validation.php(308): CodeIgniter\Validation\Rules->is_unique('shambhu@rightfu...', 'email', Array, NULL)
#5 D:\xampp\htdocs\ci4\system\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'shambhu@rightfu...', Array, Array)
#6 D:\xampp\htdocs\ci4\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#7 D:\xampp\htdocs\ci4\app\Controllers\SignupController.php(27): CodeIgniter\Controller->validate(Array)
#8 D:\xampp\htdocs\ci4\system\CodeIgniter.php(898): App\Controllers\SignupController->store()
#9 D:\xampp\htdocs\ci4\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
#10 D:\xampp\htdocs\ci4\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\xampp\htdocs\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\xampp\htdocs\ci4\system\Commands\Server\rewrite.php(43): require_once('D:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-05-03 05:34:28 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(308): CodeIgniter\Validation\Rules->is_unique('shambhu@rightfullabs.com', 'email', [...], null)
 5 SYSTEMPATH\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'shambhu@rightfullabs.com', [...], [...])
 6 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\SignupController.php(27): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\SignupController->store()
 9 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
10 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2024-05-03 05:34:33 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 D:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'ci4', 3306, '', 0)
#1 D:\xampp\htdocs\ci4\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\ci4\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 D:\xampp\htdocs\ci4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\ci4\system\Validation\Validation.php(308): CodeIgniter\Validation\Rules->is_unique('shambhu@rightfu...', 'email', Array, NULL)
#6 D:\xampp\htdocs\ci4\system\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'shambhu@rightfu...', Array, Array)
#7 D:\xampp\htdocs\ci4\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 D:\xampp\htdocs\ci4\app\Controllers\SignupController.php(27): CodeIgniter\Controller->validate(Array)
#9 D:\xampp\htdocs\ci4\system\CodeIgniter.php(898): App\Controllers\SignupController->store()
#10 D:\xampp\htdocs\ci4\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
#11 D:\xampp\htdocs\ci4\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\xampp\htdocs\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 D:\xampp\htdocs\ci4\system\Commands\Server\rewrite.php(43): require_once('D:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 D:\xampp\htdocs\ci4\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\ci4\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 D:\xampp\htdocs\ci4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\ci4\system\Validation\Validation.php(308): CodeIgniter\Validation\Rules->is_unique('shambhu@rightfu...', 'email', Array, NULL)
#5 D:\xampp\htdocs\ci4\system\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'shambhu@rightfu...', Array, Array)
#6 D:\xampp\htdocs\ci4\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#7 D:\xampp\htdocs\ci4\app\Controllers\SignupController.php(27): CodeIgniter\Controller->validate(Array)
#8 D:\xampp\htdocs\ci4\system\CodeIgniter.php(898): App\Controllers\SignupController->store()
#9 D:\xampp\htdocs\ci4\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
#10 D:\xampp\htdocs\ci4\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\xampp\htdocs\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\xampp\htdocs\ci4\system\Commands\Server\rewrite.php(43): require_once('D:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-05-03 05:34:33 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(308): CodeIgniter\Validation\Rules->is_unique('shambhu@rightfullabs.com', 'email', [...], null)
 5 SYSTEMPATH\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'shambhu@rightfullabs.com', [...], [...])
 6 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\SignupController.php(27): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\SignupController->store()
 9 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
10 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
